import React from "react";

const Definitions = () => {
  const definitions = [
    {
      title: "Account",
      desc: "A unique account created for You to access our Service or parts of our Service.",
    },
    {
      title: "Affiliate",
      desc: 'An entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
    },
    {
      title: "Application",
      desc: "Refers to MoneySmith, the software program provided by the Company.",
    },
    {
      title: "Company",
      desc: 'Referred to as either "the Company", "We", "Us" or "Our" in this Agreement, refers to TAPWALLET LIMITED, 2, MACARTHY STREET, ONIKAN, LAGOS STATE, NIGERIA.',
    },
    {
      title: "Country",
      desc: "Refers to: Nigeria",
    },
    {
      title: "Device",
      desc: "Means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
    },
    {
      title: "Personal Data",
      desc: "Any information that relates to an identified or identifiable individual.",
    },
    {
      title: "Service",
      desc: "Refers to the Application.",
    },
    {
      title: "Service Provider",
      desc: "Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
    },
    {
      title: "Usage Data",
      desc: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
    },
    {
      title: "You",
      desc: "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
    },
  ];

  return (
    <div>
      <ul className="list-disc pl-5 space-y-2">
        {definitions.map((item, index) => (
          <li key={index}>
            <strong>{item.title}:</strong> {item.desc}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Definitions;
